# Generated by Django 4.1 on 2022-08-18 00:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="card_id",
            field=models.CharField(default="card", max_length=280),
        ),
        migrations.AddField(
            model_name="card", name="own", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="card",
            name="set_id",
            field=models.ManyToManyField(to="cards.set"),
        ),
        migrations.AddField(
            model_name="set",
            name="percentCompleted",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="set",
            name="set_id",
            field=models.CharField(default="set", max_length=280),
        ),
        migrations.AddField(
            model_name="set",
            name="totalCardOwned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="set", name="totalCardSet", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="set",
            name="user_id",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
