# Generated by Django 4.1 on 2022-08-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_card_card_id_card_own_card_set_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="big_image",
            field=models.CharField(default="big", max_length=280),
        ),
        migrations.AddField(
            model_name="card",
            name="card_name",
            field=models.CharField(default="card", max_length=280),
        ),
        migrations.AddField(
            model_name="card",
            name="small_image",
            field=models.CharField(default="small", max_length=280),
        ),
        migrations.AddField(
            model_name="set",
            name="set_logo",
            field=models.CharField(default="logo", max_length=280),
        ),
    ]
